title: WattzKraken.com
description: Deep and Dark, it bellows... 🦑
baseurl: "/" 
url: "https://puddlesxxx.github.io/wattzkraken/" 
theme: jekyll-theme-cayman
author: puddles
email: puddlesxxx@gmail.com
github_username: puddlesxxx
